server:
  port: 8307
  
# Oracle Connect
spring:
  # File Size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: scott
    password: tiger  
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
  # Jpa Setting****
  jpa: 
    hibernate:
      ddl-auto: none  # create update none 
    properties:
      hibernate:
        default_batch_fetch_size: 500
      show_sql:   true    # System.out 에 하이버네이트 실행 SQL
      format_sql: true

  # view Resolver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  # gmail Transfer
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password:   # 앱비밀번호 설정해야함
    properties:
      mail:
        smtp:
          auth: true  # 오돌라이제이션 인증할거냐
          starttls.enable: true  # 소캣 시큐어 레이어 암호화할거냐
          
# Mybatis
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml            

logging.level:
  org.hibernate.SQL: debug  # logger를 통해 하이버네이트 실행 SQL